environment: production
production: true

gems:
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-paginate

url: http://www.vrmanchester.net

source: .
layouts_dir: ./_layouts
exclude: ['node_modules', 'bower.json', 'package.json', 'Rakefile', 'gulpfile.js', 'README.md']
timezone: Europe/London


defaults:
  -
    values:
      layout: "base"
